### PR TITLE
releasing binary

### PR DESCRIPTION
**Pull request by ineiti**
Releasing binaries for @nkcr

### CODE REVIEW

**Comment by gnarula** [comment]
Can we extend this to build evoting-admin binary and add a Windows build as well? There's an evoting node that uses Windows IIRC. I'd be happy to submit a PR for it

**Comment by ineiti** [comment]
The c4dt/byzcoin currently only supports a subset of dedis/cothority. The goal is to reduce the attack surface (which is still huge, I know) for running byzcoin nodes. So to have the evoting in there would require adding that, too. As the evoting is not really part of byzcoin, and only uses the skipchain, I don't think it's a good idea to do so. Unless evoting uses byzcoin, of course ;)

**Comment by gnarula** [comment]
> The c4dt/byzcoin currently only supports a subset of dedis/cothority. The goal is to reduce the attack surface (which is still huge, I know) for running byzcoin nodes. So to have the evoting in there would require adding that, too. As the evoting is not really part of byzcoin, and only uses the skipchain, I don't think it's a good idea to do so. Unless evoting uses byzcoin, of course ;)

My bad, I looked dedis/cothority/conode/conode.go's imports instead of full.go. So if I get it right, you'd suggest doing a release on dedis/cothority instead?

**Comment by ineiti** [comment]
Yes, I think there is some documentation of how to do releases for dedis/cothority. Jeff did those manually, and when C4DT took over dedis/cothority, we dropped this service :( But I think most of this github-workflow can be ported to dedis/cothority, so you have releases again. So a PR against dedis/cothority might be a good idea.

**Pull request merged**
